bot:
  token: ${BOT_TOKEN}
  name: PartyKabachok

client:
  cbr:
    base-url: ${CBR_BASE_URL:https://www.cbr.ru}
  weather:
    base-url: ${WEATHER_BASE_URL:https://api.openweathermap.org} # https://openweathermap.org/forecast16  https://openweathermap.org/forecast5
    api-key: ${WEATHER_API_KEY}


spring:
  application:
    name: kabachok-tg-bot
#logging:
#  file:
#    name: "log.log"