bot:
  token: ${BOT_TOKEN}
  name: PartyKabachok

client:
  cat-api:
    base-url: ${CAT_BASE_URL:https://api.thecatapi.com}
  cbr:
    base-url: ${CBR_BASE_URL:https://www.cbr.ru}
  weather:
    base-url: ${WEATHER_BASE_URL:https://api.openweathermap.org}
    api-key: ${WEATHER_API_KEY}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
  application:
    name: kabachok-tg-bot
